# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Label

OUTPUT_PATH = Path(__file__).parent
import os
ASSETS_PATH = os.path.join(os.path.dirname(__file__), "assets", "frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

##################################################
##################################################

window = Tk()

window.geometry("720x720")
window.configure(bg = "#222429")

canvas = Canvas(
    window,
    bg = "#222429",
    height = 720,
    width = 720,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

##################################################
##################################################

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    123.0,
    image=image_image_1
)

# -----------------------------------------------

Menu_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
x_center = canvas.winfo_reqwidth() / 2  # Obtenemos el ancho del canvas y dividimos por 2

y_offset = 20
# Usamos la posición x calculada y mantenemos la posición y original
Menu_1 = canvas.create_image(
    x_center,
    166.0 + y_offset,
    image=Menu_image_1
)

# -----------------------------------------------

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    bg="#222429"
)
button_2.place(
    x=321.0,
    y=234.0,
    width=78.0,
    height=25.0
)

# -----------------------------------------------

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
    bg="#222429"
)
button_3.place(
    x=297.0,
    y=305.0,
    width=127.0,
    height=25.0
)

# -----------------------------------------------

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat",
    bg="#222429"
)
button_4.place(
    x=329.0,
    y=376.0,
    width=63.0,
    height=25.0
)

##################################################
##################################################

canvas.create_rectangle(
    290.0,
    273.0,
    431.0,
    279.0,
    fill="#FFCC00",
    outline="")

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    168.0,
    633.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    357.99999237060547,
    627.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    424.0,
    627.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    551.0,
    627.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    491.0,
    627.0,
    image=image_image_6
)

canvas.create_rectangle(
    212.0,
    626.0,
    225.0,
    639.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    240.0,
    626.0,
    253.0,
    639.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    268.0,
    626.0,
    281.0,
    639.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    295.0,
    626.0,
    308.0,
    639.0,
    fill="#D9D9D9",
    outline="")
window.resizable(False, False)
window.mainloop()